name: Deploy MkDocs

on:
  push:
    branches:
      - main  # or master, depending on your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions 
          pip install mkdocstrings mkdocstrings-python
      
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Deploy documentation
        run: |
          # Make script executable
          chmod +x scripts/build_docs.py
          # Use our custom script to build and deploy with proper mocking
          python scripts/build_docs.py --deploy